### ISSUE TITLE
DMG background on macOS is too big

### ISSUE THREAD

**Issue by makitsune** [Hyperchroma/hyperchroma#3]
**Describe the bug**
The background for the DMG installer is far too big on macOS. It takes up the entire screen on a 1080p monitor.

**Screenshots**
![Screen Shot 2021-11-27 at 19 09 58](https://user-images.githubusercontent.com/8362329/143725372-3f1d1a69-14a1-46fc-9e8b-547eff216173.png)

**Additional Information (please complete the following information):**
- OS: Using macOS Monterey on an M1 MacBook

**Comment by aeroheim** [comment]
I updated the dmg background to a new 540x380 image (looks to be the default/recommended resolution).

Issue should be resolved in the 0.9.1-beta release. Please re-open if you still see the issue.
